### ISSUE TITLE
Test mockAnswers as the expected.

### ISSUE THREAD

**Issue by kepop1** [Cratesy/team-generator#2]
https://github.com/Cratesy/team-generator/blob/661c50875bc4fd797a45e859505013672820c5ce/__tests__/employee.test.js#L18-L23

The expectations used here should have the assertion in a variable:

```
const expected = {
  name: "mike",
  id: "31",
  email: "mike31@hotmail.com",
}
expect(employee).toEqual(expected)
```

Just keeps the assertion statement cleaner and easier to read - could change this across the other tests

**Comment by Cratesy** [comment]
have fixed this and pushed it [https://github.com/Cratesy/team-generator/commit/284bc807d4fb35c881199be6aa1ecc36f695fc18](url)
